@startuml
left to right direction
skinparam packageStyle rect
actor клиент
actor банк
rectangle Банкомат {
  клиент-- (Проверка баланса)
  клиент-- (Снятие наличных)
  клиент-- (Положить наличные на карту)
  (Снятие наличных) -> (Проверка баланса) : extends
  банк-- (проверить остатки наличных)
}
@enduml
