@startuml
left to right direction
skinparam packageStyle rect
actor клиент
actor банк
rectangle Банкомат {
  клиент-- (Проверка наличных)
  клиент-- (Снять наличные с карты)
  клиент-- (Положить наличные на карту)
  клиент-- (Оплата коммунальных услуг)
  клиент-- (Оплата штрафа)
  клиент-- (Взнос по кредиту)
  клиент-- (Положить деньги на телефон)
  (Оплата коммунальных услуг) <- (Проверка наличных) :extend
  (Снять наличные с карты) <- (Проверка наличных) :extend
  (Оплата штрафа) <- (Проверка наличных) :extend
  (Взнос по кредиту) <- (Проверка наличных) :extend
  (Положить деньги на телефон) <- (Проверка наличных) :extend
  банк -- (Проверка остатка)
  банк -- (Отказ в транзакции)
  банк -- (Проверка личных данных)
  (Отказ в транзакции) <- (Проверка остатка) : extend
  (Отказ в транзакции) <- (Проверка личных данных) : extend
}
@enduml
