@startuml "Банкомат классы"
left to right direction 
node Сеть
node Сервер_Банка
node Банкомат_1
node Банкомат_2
node Банкомат_3
artifact Адрес_1
artifact Адрес_2
artifact Адрес_3

Сервер_Банка -> Сеть
Сеть --> Банкомат_1
Сеть --> Банкомат_2
Сеть --> Банкомат_3
Банкомат_1 -> Адрес_1
Банкомат_2 -> Адрес_2
Банкомат_3 -> Адрес_3
@enduml
