@startuml asd
skinparam packageStyle rect
actor Клиент
participant Банкомат
participant Терминал
participant Контроллер_банка
participant Итог
Клиент -> Банкомат: Карта вставлена
activate Банкомат
activate Клиент
Банкомат -> Терминал: Запросить пин код
activate Терминал
Терминал -> Контроллер_банка: Проверить пин код
deactivate Терминал
activate Контроллер_банка
Контроллер_банка -> Терминал: Результат проверки
deactivate Контроллер_банка
Банкомат -> Терминал: запросить операцию
activate Терминал
Клиент -> Терминал: Выбор операции
Банкомат -> Терминал: запросить сумму
deactivate Терминал
Клиент -> Терминал: Ввод суммы
activate Терминал
Терминал -> Контроллер_банка: Проверить баланс
deactivate Терминал
activate Контроллер_банка
Контроллер_банка -> Терминал: Результат проверки
Терминал -> Итог: Выполнение операции
activate Итог
Банкомат -> Клиент: Выдать карту

@enduml
