@startuml "Банкомат классы"
left to right direction

class Клиент{
  ФИО : string
  Паспортные_данные : string
  Дата_рождения : datatime
  Номер_банковской_карты : varchar
  Телефон : varchar
  Проверка_наличных()
  Снять_наличные_с_карты()
  Положить_наличные_на_карту()
  Оплата_коммунальных_услуг()
  Оплата_штрафа()
  Взнос_по_кредиту()
  Положить_деньги_на_телефон()


}
class Банк{
  Название : string
  Местоположение : string
  Отказать_в_транзакции()
  Проверка_личных_данных()
  Проверка_остатка()
  Одобрение_транзакции()
}
Клиент <-- Банк: Ответ на транзакцию
Банк <-- Клиент: Запрос банку
@enduml
